### ISSUE TITLE
Version check string is different in new Defender

### ISSUE THREAD

**Issue by macvfx** [tuxudo/ms_defender#1]
`mdatp health check

New flavour: "appVersion" vs old "versionEngine"

Original flavour: "versionEngine"

cloudAutomaticSampleSubmission          : true
cloudDiagnosticEnabled                  : true
cloudEnabled                            : true
definitionsUpdated                      : "1593028659306"
definitionsUpdatedMinutesAgo            : 150
definitionsVersion                      : 80892
edrDeviceTags                           : []
edrEarlyPreviewEnabled                  : "disabled"
edrMachineId                            : "7ca99266dd3abbaf3c92e6e6d7e0f93c2c8565fe"
healthy                                 : true
licensed                                : true
logLevel                                : "info"
machineGuid                             : "028bd76b-237e-5cd5-9996-015e83e2ff23"
orgId                                   : "b0a1886e-17c9-46ad-b9b7-2ab6df986f99"
realTimeProtectionAvailable             : true
realTimeProtectionEnabled               : true
releaseRing                             : "Production"
versionEngine                           : "100.90.27"

New flavour: "appVersion"

appVersion                                  : "101.01.54"
cloudAutomaticSampleSubmissionConsent       : "safe"
cloudDiagnosticEnabled                      : false
cloudEnabled                                : true
definitionsUpdated                          : "1593037650386"
definitionsUpdatedMinutesAgo                : 0
definitionsVersion                          : "80893"
edrDeviceTags                               : []
edrEarlyPreviewEnabled                      : "disabled"
edrMachineId                                : "3f67feba328240c95bd3164f2b91b5e273af925f"
engineVersion                               : "3.0"
healthy                                     : true
licensed                                    : true
logLevel                                    : "info"
machineGuid                                 : "b1dfb93e-e27f-5e9f-97a7-8cf3578aa374"
orgId                                       : "b0a1886e-17c9-46ad-b9b7-2ab6df986f99"
realTimeProtectionAvailable                 : true
realTimeProtectionEnabled                   : true
realTimeProtectionSubsystem                 : "kernel_extension"
releaseRing                                 : "Production"`

**Comment by tuxudo** [comment]
Resolved with version 1.2 of module
