### ISSUE TITLE
ms_defender (Master is Python 3)

### ISSUE THREAD

**Issue by tuxudo** [tuxudo/ms_defender#6]
tuxudo/ms_defender

**Comment by sodos2747** [comment]
Any reason pointing on Python3 ? The template fails but works when I change Python3 to Python2 in scripts.
#!/usr/local/munkireport/munkireport-python3 
I am just curious and thank you indeed with all your other MunkiReport modules

**Comment by tuxudo** [comment]
The Master branch is using Python 3 in preparation for upgrading the module to MunkiReport v6. When manually downloading the module, use the v2.0 release.
